# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: liferay-pvc
#   namespace: default
#   labels:
#     app: liferay
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: manual
# templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: liferay-pvc
spec:
  accessModes:
    {{ toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}